/*
 * prog.c: dosmc sample program
 * by ptss@fazekas.hu at Thu Jun 25 12:23:58 CEST 2020
 *
 * Compile to prog.exe: ./dosmc prog.c
 * Compile to prog.com: ./dosmc -bt=com prog.c
 * Run it with `dosbox .', then `prog.exe'.
 * Expected output: ZYfghiHello!
 */

#include <dosmc.h>

/* Only with static, both get_str and the string literal will be optimized away. */
static char *example_get_str(void) {
  return "LONG STRING";
}

int double_int(int x) {
  return x * 2;
}

int add(int a, int b, int(*f)(int)) {
  return a + f(b);
}

unsigned fact(unsigned n) {
  unsigned result = 1;
  for (; n > 1; --n) {
    result *= n;
  }
  return result;
}

const int base = 2;
const char basex = 4;
const int basey = 5;

char hi[137], ho;
int answer;

int main(void) {
  char msg[3];
  msg[0] = 'Z'; msg[1] = 'Y'; msg[2] = '$';
  _printmsgx(msg);
  /* !! prog.o (generated by the compiler contains WORD-aligned segments) */
  /* !! How to get command-line arguments? From PSP 0x80 -- or CMDLINE environment variable. */
  /* !! Initialize es in crt0? (cstrt086.asm doesn't do it) */
  /* !! Pack relocations, save 16 bytes. Maybe get rid of single relocation (mov ax, DGROUP)? */
  /* !! Remove single relocation (mov ax, DGROUP) */
  /* !! Why are strings aligned to 2? Is it segment alignment? */
  _printmsgx("abcdefghi$" + add(1, 2, double_int));  /* "fghi" */
  _printmsgx("++Hello!\r\n$" + base + answer);
  return add(7, 8, double_int);
}
